# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v2
name: openbao
version: 0.15.1
appVersion: v2.2.2
kubeVersion: ">= 1.30.0-0"
description: Official OpenBao Chart
home: https://github.com/openbao/openbao-helm
icon: https://github.com/openbao/artwork/blob/main/color/openbao-color.svg
keywords:
  [
    "vault",
    "openbao",
    "security",
    "encryption",
    "secrets",
    "management",
    "automation",
    "infrastructure",
  ]
sources:
  - https://github.com/openbao/openbao-helm
annotations:
  charts.openshift.io/name: Openbao

maintainers:
  - name: OpenBao
    email: openbao-security@lists.openssf.org
    url: https://openbao.org
